spring:
  application:
    name: flashhsk

  datasource:
    url: jdbc:sqlite:src/main/resources/db/flashcards.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate

# Enter frontend URL
FRONTEND_URL: http://localhost:5173